version: "2"
services:
  db:
    image: redis
    volumes:
      - /tmp/ip_pool_data_backup:/data
    restart: always

  pool:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/ip_pool
    links:
      - db
    depends_on:
      - db
    command: python ./run.py
    restart: always